[package]
name = "vulcan_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
glam = "0.28.0"
log = "0.4.22"
pollster = "0.3.0"
vulkano = {version = "0.34.1", features=["macros"]}
vulkano-shaders = "0.34.0"
winit = {version = "0.30.4", features = ["rwh_05"]}
